---
name: security

on:
  workflow_dispatch:

permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

jobs:
  dependencies-analysis:
    name: DependenciesAnalysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: upload SARIF to security dashboard
        uses: github/codeql-action/upload-sarif@65216971a11ded447a6b76263d5a144519e5eee1 # codeql-bundle-v2.25.2
        with:
          sarif_file: DependenciesAnalysisFull.sarif
          category: dependencies-analysis

  source-code-analysis:
    name: SourceCodeAnalysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:40579a2e70910d891959a4868711ba0399293949a2f1f141ddb5002d5fc7dd0f
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: run semgrep
        run: |
          semgrep scan \
            --config .semgrep \
            --sarif \
            --output SourceCodeAnalysisFull.sarif \
            .

      - name: upload SARIF to security dashboard
        uses: github/codeql-action/upload-sarif@65216971a11ded447a6b76263d5a144519e5eee1 # codeql-bundle-v2.25.2
        with:
          sarif_file: SourceCodeAnalysisFull.sarif
          category: source-code-analysis
